database:
  driverClass: org.sqlite.JDBC

  # the JDBC URL
  url: jdbc:sqlite:dev.db

  # the JDBC user
  user: jslater
#  url: "jdbc:sqlite::memory:"
  properties:
    charSet: UTF-8
server:
  rootPath: /v1/public/*
